FROM eriksdigital.azurecr.io/openjdk/11u104-jre-slim
RUN apt update && apt-get install wget curl -y

ENV APP_NAME guided-selling-plastics-customizer
ENV JAVA_OPTS="-Xms1024m -Xmx1024m -Dlogging.json=true"
COPY build/libs/${APP_NAME}*.jar /${APP_NAME}.jar
COPY src/main/docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY src/main/docker/create_properties.sh /create_properties.sh
RUN touch /${APP_NAME}.jar && mkdir -p /config
WORKDIR /

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "java ${JAVA_OPTS} -jar /${APP_NAME}.jar" ]